#pragma once
#define UPDATE_BIAS_BLKSIZE 384
#define UPDATE_ETA_BLKSIZE 384
#define DECIMATE_2_BLKSIZE 384
#define CALC_PI_VALUES_BLKSIZE 384
static const char *TUNING_PARAMETERS = "UPDATE_BIAS_BLKSIZE 384\nUPDATE_ETA_BLKSIZE 384\nDECIMATE_2_BLKSIZE 384\nCALC_PI_VALUES_BLKSIZE 384\n";
