#pragma once
#define DEF_THREADS_PER_BLOCK 1024
#define UPDATE_THREADS_PER_BLOCK 1024
#define HCD_THREADS_PER_BLOCK 512
#define COPY_INV_THREADS_PER_BLOCK 512
#define STORE_INV_THREADS_PER_BLOCK 512
#define GEP_INV_THREADS_PER_BLOCK 512
static const char *TUNING_PARAMETERS = "DEF_THREADS_PER_BLOCK 1024\nUPDATE_THREADS_PER_BLOCK 1024\nHCD_THREADS_PER_BLOCK 512\nCOPY_INV_THREADS_PER_BLOCK 512\nSTORE_INV_THREADS_PER_BLOCK 512\nGEP_INV_THREADS_PER_BLOCK 512\n";
