#pragma once
#define GPU_NAME "Tesla K40c"
#define GPU_VERSION_MAJOR 3
#define GPU_VERSION_MINOR 5
#define RT_VERSION 5050
#define DRV_VERSION 6050

#define CHECK_TRIANGLES_BLKSIZE 352
#define REFINE_BLKSIZE 512
static const char *TUNING_PARAMETERS = "CHECK_TRIANGLES_BLKSIZE 352\nREFINE_BLKSIZE 512\n";
