#pragma once
#define GPU_NAME "Tesla K40c"
#define GPU_VERSION_MAJOR 3
#define GPU_VERSION_MINOR 5
#define RT_VERSION 5050
#define DRV_VERSION 6050

#define FINDCOMPMINTWO_BLKSIZE 192
#define KCONF_BLKSIZE 32
static const char *MST_TUNING_PARAMETERS = "FINDCOMPMINTWO_BLKSIZE 192\nKCONF_BLKSIZE 32\n";
