#pragma once
#define GPU_NAME "Tesla K40c"
#define GPU_VERSION_MAJOR 3
#define GPU_VERSION_MINOR 5
#define RT_VERSION 5050
#define DRV_VERSION 6050

#define CALC_PI_VALUES_BLKSIZE 384
#define UPDATE_ETA_BLKSIZE 288
#define UPDATE_BIAS_BLKSIZE 96
#define DECIMATE_2_BLKSIZE 352
static const char *TUNING_PARAMETERS = "CALC_PI_VALUES_BLKSIZE 384\nUPDATE_ETA_BLKSIZE 288\nUPDATE_BIAS_BLKSIZE 96\nDECIMATE_2_BLKSIZE 352\n";
