#pragma once
#define UPDATE_BIAS_BLKSIZE 128
#define UPDATE_ETA_BLKSIZE 64
#define DECIMATE_2_BLKSIZE 352
#define CALC_PI_VALUES_BLKSIZE 224
static const char *TUNING_PARAMETERS = "UPDATE_BIAS_BLKSIZE 128\nUPDATE_ETA_BLKSIZE 64\nDECIMATE_2_BLKSIZE 352\nCALC_PI_VALUES_BLKSIZE 224\n";
