#pragma once
#define GPU_NAME "Quadro 6000"
#define GPU_VERSION_MAJOR 2
#define GPU_VERSION_MINOR 0
#define RT_VERSION 5050
#define DRV_VERSION 6050

#define DEF_THREADS_PER_BLOCK 480
#define UPDATE_THREADS_PER_BLOCK 992
#define HCD_THREADS_PER_BLOCK 256
#define COPY_INV_THREADS_PER_BLOCK 512
#define STORE_INV_THREADS_PER_BLOCK 352
#define GEP_INV_THREADS_PER_BLOCK 512
static const char *TUNING_PARAMETERS = "DEF_THREADS_PER_BLOCK 480\nUPDATE_THREADS_PER_BLOCK 992\nHCD_THREADS_PER_BLOCK 256\nCOPY_INV_THREADS_PER_BLOCK 512\nSTORE_INV_THREADS_PER_BLOCK 352\nGEP_INV_THREADS_PER_BLOCK 512\n";
